tasks:

  - source: convert2nexus.py
    product:
      nb: products/convert2nexus.ipynb
    params:
      root_folder: "{{root_folder}}"
      template_metadata: "{{template_metadata}}"
      output_folder: "{{output_folder}}"
      multidimensional: "{{multidimensional}}"

