# GENERATED FILE - DO NOT EDIT.
# Regenerate with: poetry run python dev-tools/gen_nexus_models.py --appdef NXraman
# Source: NeXus application definition "NXraman", resolved via
# pynxtools.nexus.nexus_tree.generate_tree_from (walks the NXDL `extends` chain).

from __future__ import annotations

from typing import ClassVar, Dict, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from pyambit.datamodel import Value

from pyambit.nexus_models.base.nx_data import NXData
from pyambit.nexus_models.base.nx_instrument import NXInstrument
from pyambit.nexus_models.base.nx_process import NXProcess
from pyambit.nexus_models.base.nx_sample import NXSample


class NXRaman(BaseModel):
    """An application definition for Raman spectroscopy experiments. This application definition supports a wide range of Raman spectroscopy experiments. These may be as simple as acquiring a single Raman spectrum from spontaneous Raman scattering, or as complex as Raman imaging with a Raman spectrometer. The scope also includes surface- and tip-enhanced Raman techniques, X-ray Raman scattering, resonant Raman scattering, and multidimensional Raman spectra collected under varying conditions such as temperature, pressure, or electric field. The application definition comprises two main components: 1. Structures defined in NXoptical_spectroscopy: * Instrument configuration and data calibration * Sensors monitoring sample or beam conditions 2. Structures specified and extended in NXraman: * Description of the experiment type * Metadata and configuration of the optical setup (e.g., source, monochromator, detector, waveplate, lens) * Detailed description of beam properties and their interaction with the sample * Sample-specific information Information on Raman spectroscopy are provided in: General * Lewis, Ian R.; Edwards, Howell G. M. Handbook of Raman Spectroscopy ISBN 0-8247-0557-2 Raman scattering selection rules * Dresselhaus, M. S.; Dresselhaus, G.; Jorio, A. Group Theory - Application to the Physics ofCondensed Matter ISBN 3540328971 Semiconductors * Manuel Cardona Light Scattering in Solids I eBook ISBN: 978-3-540-37568-5 DOI: https://doi.org/10.1007/978-3-540-37568-5 * Manuel Cardona, Gernot Güntherodt Light Scattering in Solids II eBook ISBN: 978-3-540-39075-6 DOI: https://doi.org/10.1007/3-540-11380-0 * See as well other Books from the "Light Scattering in Solids" series: III: Recent Results IV: Electronic Scattering, Spin Effects, SERS, and Morphic Effects V: Superlattices and Other Microstructures VI: Recent Results, Including High-Tc Superconductivity VII: Crystal-Field and Magnetic Excitations VIII: Fullerenes, Semiconductor Surfaces, Coherent Phonons IX: Novel Materials and Techniques Glasses, Liquids, Gasses, ... Review articles: Stimulated Raman scattering, Coherent anti-Stokes Raman scattering, Surface-enhanced Raman scattering, Tip-enhanced Raman scattering * https://doi.org/10.1186/s11671-019-3039-2"""

    model_config = ConfigDict(populate_by_name=True)
    NX_CLASS: ClassVar[str] = 'NXraman'

    definition: Optional[Union[str, Value]] = Field(default=None, alias='definition', description="An application definition for Raman spectroscopy. Allowed values: ['NXraman'].", json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    title: Optional[Union[str, Value]] = Field(default=None, alias='title', description='Extended title for entry', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    experiment_type: Optional[Union[str, Value]] = Field(default=None, alias='experiment_type', description="Specify the type of the optical experiment. You may specify fundamental characteristics or properties in the experimental sub-type. Allowed values: ['Raman spectroscopy'].", json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    raman_experiment_type: Optional[Union[str, Value]] = Field(default=None, alias='raman_experiment_type', description="Specify the type of Raman experiment. Suggested values: ['in situ Raman spectroscopy', 'resonant Raman spectroscopy', 'non-resonant Raman spectroscopy', 'Raman imaging', 'tip-enhanced Raman spectroscopy (TERS)', 'surface-enhanced Raman spectroscopy (SERS)', 'surface plasmon polariton enhanced Raman scattering (SPPERS)', 'hyper Raman spectroscopy (HRS)', 'stimulated Raman spectroscopy (SRS)', 'inverse Raman spectroscopy (IRS)', 'coherent anti-Stokes Raman spectroscopy (CARS)'].", json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    instrument: Dict[str, NXInstrument] = Field(default_factory=dict, alias='INSTRUMENT', description='Metadata of the setup, its optical elements and physical properties which defines the Raman measurement.', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    start_time: Optional[Union[str, Value]] = Field(default=None, alias='start_time', description='Datetime of the start of the measurement. Should be a ISO8601 date/time stamp. It is recommended to add an explicit time zone, otherwise, the local time zone is assumed per ISO8601. It is required to enter at least one of both measurement times, either "start_time" or "end_time".', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    end_time: Optional[Union[str, Value]] = Field(default=None, alias='end_time', description='Datetime of the end of the measurement. Should be a ISO8601 date/time stamp. It is recommended to add an explicit time zone, otherwise the local time zone is assumed per ISO8601. It is required to enter at least one of both measurement times, either "start_time" or "end_time".', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    identifier_experiment: Optional[Union[str, Value]] = Field(default=None, alias='identifier_experiment', description='An identifier for a (persistent) resource. An identifier, provided by some authority, that has been assigned to an object described by this ``NXobject``. To be useful, the identifier must not be reassigned to a different real-world object. It is typical for there to be some mechanism to resolve an identifier, obtaining metadata about the object. Identifiers for which some guarantees exist regarding this resolution process are called persistent identifiers. Persistent identifiers are also known as PIDs.', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    sample: Dict[str, NXSample] = Field(default_factory=dict, alias='SAMPLE', description='Properties of the sample, such as sample type, layer structure, chemical formula, atom types, its history etc. Information about the sample stage and sample environment should be described in ENTRY/INSTRUMENT/sample_stage.', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    data: Dict[str, NXData] = Field(default_factory=dict, alias='DATA', description='Here generic types of data may be saved. This may refer to data derived from single or multiple raw measurements (i.e. several intensities are evaluated for different parameters: ellipsometry -> psi and delta) - i.e. non-raw data. As well plottable data may be stored/linked here, which provides the most suitable representation of the data (for the respective community). You may provide multiple instances of NXdata', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
    measurement_data_calibration_type: Dict[str, NXProcess] = Field(default_factory=dict, alias='measurement_data_calibration_TYPE', description='The :ref:`NXprocess` class describes an operation used to process data as part of an analysis workflow, providing information such as the software used, the date of the operation, the input parameters, and the resulting data.', json_schema_extra={'nx_unit_category': None, 'nx_is_attribute': False})
